name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@master
        with:
          node-version: 21
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
